######################## default configuration ####################
baseURL = "https://gladbooks.ru"
languageCode = "ru-Ru"
title = "Adrian Hugo | E-commerce template"
theme = "adrian-hugo"
summaryLength = "20"
paginate = 6
# disqusShortname = "themefisher-template"    #get your shortname form : disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45

############################ Output ###############################
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

############################# Taxonomies ###########################
[taxonomies]
category = "categories"
format = "formats"
color = "colors"
size = "sizes"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
# [[params.plugins.css]]
# link = "https://cdn.snipcart.com/themes/v3.1.0/default/snipcart.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/SyoTimer/jquery.syotimer.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
# [[params.plugins.js]]
# link = "https://cdn.snipcart.com/themes/v3.1.0/default/snipcart.js"
[[params.plugins.js]]
link = "plugins/instafeed-js/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/inputmask/inputmask.js"
# [[params.plugins.js]]
# link = "plugins/google-map/gmap.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Магазин"
URL = "shop/"
weight = 1

[[menu.main]]
name = "О нас"
URL = "about/"
weight = 2

[[menu.main]]
name = "Faq"
URL = "faq/"
weight = 3

[[menu.main]]
name = "Контакты"
URL = "contact/"
weight = 4


# category menu
[[menu.category]]
name = "Олкотт"
URL = "categories/олкотт/"
weight = 10

[[menu.category]]
name = "Портер"
URL = "categories/портер/"
weight = 20

# useful links
[[menu.useful_links]]
name = "Магазин"
URL = "shop/"
weight = 1

[[menu.useful_links]]
name = "О нас"
URL = "about/"
weight = 2

[[menu.useful_links]]
name = "Faq"
URL = "faq/"
weight = 3

[[menu.useful_links]]
name = "Контакты"
URL = "contact/"
weight = 4

# footer menu
[[menu.footer]]
name = "Политика Конфиденциальности"
URL = "privacy-policy/"
weight = 1

[[menu.footer]]
name = "Условия использования"
URL = "terms-conditions/"
weight = 2

[[menu.footer]]
name = "Политика использования файлов cookie"
URL = "cookie-policy/"
weight = 3

[[menu.footer]]
name = "Условия продажи"
URL = "terms-of-sale/"
weight = 4

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Главная"
# Meta data
description = "This is meta description"
# author = "Themefisher"
# snipcart public api key
# snipcartAPI = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
currency = "₽"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = "0124857985320"
email = "demo@email.com"
location = "Dhaka, Bangladedsh"
# contact form action
contactFormAction = "#" # contact form works with : https://formspree.io
# footer content
footer_content = "Iste dolores iure quis excepturi, deserunt praesentium."
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [@creio](https://creio.ctlos.ru)"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

# opening hours
[[params.openingHour]]
day = "Понедельник-Пятница"
time = "8.00-20.00"

[[params.openingHour]]
day = "Суббота"
time = "10.00-20.00"

[[params.openingHour]]
day = "Воскресенье"
time = "12.00-20.00"

[markup.goldmark.renderer]
  unsafe = true
